const state = { langCode: localStorage.getItem('langCode') || 'ko' };
const byId = (id) => document.getElementById(id);
function getLangEntry() { return (window.SITE_LANGUAGES || []).find(x => x.code === state.langCode) || (window.SITE_LANGUAGES || [])[0]; }
function t() { const entry = getLangEntry(); return window.SITE_TRANSLATIONS?.[entry?.fileKey] || window.SITE_TRANSLATIONS?.korea; }
function pageId() { return (location.hash || '#home').replace('#', '') || 'home'; }
function link(page) { return `#${page}`; }
function renderLanguageSelect() { const sel = byId('languageSelect'); sel.innerHTML = ''; (window.SITE_LANGUAGES || []).forEach(l => { const opt = document.createElement('option'); opt.value = l.code; opt.textContent = l.label; sel.appendChild(opt); }); sel.value = getLangEntry()?.code || 'ko'; sel.onchange = () => { state.langCode = sel.value; localStorage.setItem('langCode', state.langCode); render(); }; }
function renderNav() { const nav = byId('mainNav'); const data = t(); nav.innerHTML = data.menus.map(m => `<div class="nav-item"><a class="nav-link" href="${link(m.page)}">${m.label}</a>${m.children ? `<div class="sub-menu">${m.children.map(c => `<a href="${link(c.page)}">${c.label}</a>`).join('')}</div>` : ''}</div>`).join(''); }
function card(item) { return `<article class="card"><img src="${item.image || 'assets/images/service-room.svg'}" alt=""><span class="tag">${item.title}</span><h3>${item.title}</h3><p>${item.description}</p>${item.page ? `<p style="margin-top:14px"><a class="secondary-button small" href="${link(item.page)}">${t().common.learnMore}</a></p>` : ''}</article>`; }
function renderHome() { const data = t(); const h = data.pages.home.hero; const s = data.pages.home.sections; return `<section class="hero"><div><p class="eyebrow">${h.eyebrow}</p><h1>${h.title}</h1><p class="lead">${h.description}</p><div class="hero-actions"><a class="primary-button" href="#consultation">${data.common.getStarted}</a><a class="secondary-button" href="#services">${data.common.learnMore}</a></div><div class="notice">의료·시술 관련 내용은 정보 제공용입니다. 실제 결정은 자격 있는 전문가와 상담 후 진행하세요.</div></div><div class="hero-card"><img src="${h.image}" alt=""></div></section>${section(s.storiesTitle, data.stories, 'grid')}${section(s.servicesTitle, data.cards, 'grid')}${section(s.testimonialsTitle, data.testimonials.map(x => ({ title: x.name, description: '“' + x.text + '”' })), 'grid')}${section(s.whyTitle, data.why, 'grid four')}${steps(s.howTitle, data.steps)}${section(s.dealsTitle, data.deals, 'grid')}${section(s.insightsTitle, data.insights, 'grid')}`; }
function section(title, items, cls = 'grid') { return `<section class="section"><div class="section-header"><h2>${title}</h2></div><div class="${cls}">${items.map(card).join('')}</div></section>`; }
function steps(title, items) { return `<section class="section steps"><div class="section-header"><h2>${title}</h2></div><div class="grid four">${items.map(i => `<article class="card step"><div><h3>${i.title}</h3><p>${i.description}</p></div></article>`).join('')}</div></section>`; }
function renderGeneric(id) { const data = t(); const p = data.pages[id] || data.pages.home; const extra = id === 'consultation' ? consultForm() : `<div class="grid">${(id === 'services' ? data.cards : id === 'stories' ? data.stories : id === 'resources' ? data.insights : data.why).map(card).join('')}</div>`; return `<section class="page-hero"><div class="content-block"><p class="eyebrow">Nana Beauty & Care Service</p><h1>${p.title}</h1><p class="lead">${p.description}</p><div class="hero-actions"><a class="primary-button" href="#consultation">${data.common.freeConsultation}</a><a class="secondary-button" href="#home">HOME</a></div></div><div class="hero-card"><img src="${p.image}" alt=""></div></section><section class="section">${extra}</section>`; }
function consultForm() { const f = t().form; return `<form class="consult-form" onsubmit="event.preventDefault(); alert('현재 템플릿은 저장 기능 없이 화면 테스트만 합니다. 실제 서비스에서는 Formspree, Google Forms, 서버리스 함수 중 하나를 연결하세요.');"><input required placeholder="${f.name}"><input required placeholder="${f.contact}"><select><option>${f.service}</option><option>Spa</option><option>Massage</option><option>Beauty Care</option></select><textarea rows="6" placeholder="${f.message}"></textarea><button class="primary-button" type="submit">${f.submit}</button></form>`; }
function renderFooter() { const data = t(); const f = data.footer; byId('footer').innerHTML = `<div class="footer-grid"><div><h3>${f.company}</h3><p class="footer-muted">${f.address}</p></div><div><h4>${f.resources}</h4><a href="#resources">Resources</a><a href="#packages">Packages</a></div><div><h4>${f.about}</h4><a href="#about">About</a><a href="#contact">Contact</a></div><div><h4>${f.policy}</h4><a href="#">Terms</a><a href="#">Privacy</a></div></div><p class="footer-muted">${f.copyright}</p>`; }
function render() { renderLanguageSelect(); renderNav(); document.querySelectorAll('[data-i18n="brand.name"]').forEach(el => el.textContent = t().brand.name); document.querySelectorAll('[data-i18n="common.freeConsultation"]').forEach(el => el.textContent = t().common.freeConsultation); const id = pageId(); byId('app').innerHTML = id === 'home' ? renderHome() : renderGeneric(id); renderFooter(); byId('mainNav').classList.remove('open'); }
window.addEventListener('hashchange', render); byId('mobileMenuButton').onclick = () => byId('mainNav').classList.toggle('open'); render();
